/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import model.City;
import model.Community;
import model.Encounter;
import model.House;
import model.PatientDirectory;
import model.Person;
import model.PersonDirectory;
import model.VitalSigns;

/**
 *
 * @author murali
 */
public class mainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form mainJFrame
     */
    
    PersonDirectory pd;
    Encounter e;
    PatientDirectory patdir;
    VitalSigns vs;
    House house;
    City city;
    Community c;
    
    public mainJFrame() {
        initComponents();
        
        pd = new PersonDirectory();
        e = new Encounter();
        patdir = new PatientDirectory();
        vs=new VitalSigns();
        prePopulatePerson();
        house = new House();
        city = new City();
        c = new Community();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane2 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnViewPatient = new javax.swing.JButton();
        btnViewPerson = new javax.swing.JButton();
        btnVisitDoctor = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(204, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/Stethoscope.jpeg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 61, -1, 819));

        jSplitPane2.setRightComponent(jPanel1);

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));

        btnViewPatient.setText("VIEW PATIENT");
        btnViewPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewPatientActionPerformed(evt);
            }
        });

        btnViewPerson.setText("VIEW PERSON");
        btnViewPerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewPersonActionPerformed(evt);
            }
        });

        btnVisitDoctor.setText("VISIT DOCTOR");
        btnVisitDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisitDoctorActionPerformed(evt);
            }
        });

        jButton1.setText("COMMUNITIES");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("SYSTEM");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnVisitDoctor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnViewPatient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnViewPerson, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnViewPatient, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnViewPerson, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnVisitDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(579, Short.MAX_VALUE))
        );

        jSplitPane2.setLeftComponent(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane2)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane2))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewPatientActionPerformed

        PatientJPanel patientPanel = new PatientJPanel(patdir,vs,e);
        jSplitPane2.setRightComponent(patientPanel);
    }//GEN-LAST:event_btnViewPatientActionPerformed

    private void btnViewPersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewPersonActionPerformed

        PersonJPanel personPanel = new PersonJPanel(pd);
        jSplitPane2.setRightComponent(personPanel);
    }//GEN-LAST:event_btnViewPersonActionPerformed

    private void btnVisitDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisitDoctorActionPerformed
        VisitDoctorJPanel doctorPanel = new VisitDoctorJPanel(pd, patdir,vs,e,c);
        jSplitPane2.setRightComponent(doctorPanel);
    }//GEN-LAST:event_btnVisitDoctorActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        CommunitiesJPanel CommunityPanel = new CommunitiesJPanel(house, city, pd, patdir,vs,e);
        jSplitPane2.setRightComponent(CommunityPanel);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        SystemJPanel systemPanel = new SystemJPanel(patdir,pd);
        jSplitPane2.setRightComponent(systemPanel);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnViewPatient;
    private javax.swing.JButton btnViewPerson;
    private javax.swing.JButton btnVisitDoctor;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSplitPane jSplitPane2;
    // End of variables declaration//GEN-END:variables

    private void prePopulatePerson() {
        
    String firstName;
    String lastName;
    int age;
    String houseNumber;
    int pin;
    String houseName;
    String city;
    
    Person p = pd.addPerson(firstName="Murali",lastName="Krishna",age=24,houseNumber="3",pin=22150,houseName="143 Park Drive", city="Boston");
    p.setFirstName(firstName);
    p.setLastName(lastName);
    p.setAge(age);
    p.setHouseName(houseName);
    p.setHouseNumber(houseNumber);
    p.setPin(pin);
    p.setCity(city);
    
    Person p1 = pd.addPerson(firstName="John",lastName="Doe",age=78,houseNumber="3",pin=22150,houseName="143 Park Drive",city="Boston");
    p1.setFirstName(firstName);
    p1.setLastName(lastName);
    p1.setAge(age);
    p1.setHouseName(houseName);
    p1.setHouseNumber(houseNumber);
    p1.setPin(pin);
    p1.setCity(city);
    
    Person p2 = pd.addPerson(firstName="James",lastName="K",age=27,houseNumber="12",pin=22150,houseName="Boylston st",city="Boston");
    p2.setFirstName(firstName);
    p2.setLastName(lastName);
    p2.setAge(age);
    p2.setHouseName(houseName);
    p2.setHouseNumber(houseNumber);
    p2.setPin(pin);
    p2.setCity(city);
    
    Person p3 = pd.addPerson(firstName="Yash",lastName="Sri",age=50,houseNumber="12",pin=22150,houseName="Boylston st",city="Boston");
    p3.setFirstName(firstName);
    p3.setLastName(lastName);
    p3.setAge(age);
    p3.setHouseName(houseName);
    p3.setHouseNumber(houseNumber);
    p3.setPin(pin);
    p3.setCity(city);
    
    Person p4 = pd.addPerson(firstName="James",lastName="Mathew",age=18,houseNumber="123",pin=12345,houseName="Newark st",city="Boston");
    p4.setFirstName(firstName);
    p4.setLastName(lastName);
    p4.setAge(age);
    p4.setHouseName(houseName);
    p4.setHouseNumber(houseNumber);
    p4.setPin(pin);
    p4.setCity(city);
    
    Person p5 = pd.addPerson(firstName="Matt",lastName="Damon",age=80,houseNumber="1",pin=50001,houseName="Newark st",city="Chicago");
    p5.setFirstName(firstName);
    p5.setLastName(lastName);
    p5.setAge(age);
    p5.setHouseName(houseName);
    p5.setHouseNumber(houseNumber);
    p5.setPin(pin);
    p5.setCity(city);
    
    Person p6 = pd.addPerson(firstName="Raj",lastName="Mahesh",age=80,houseNumber="08",pin=50001,houseName="Temple Town",city="Chicago");
    p6.setFirstName(firstName);
    p6.setLastName(lastName);
    p6.setAge(age);
    p6.setHouseName(houseName);
    p6.setHouseNumber(houseNumber);
    p6.setPin(pin);
    p6.setCity(city);
    
    }
}
