/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Patient;
import model.PatientDirectory;
import model.Person;
import model.PersonDirectory;
import model.VitalSigns;

/**
 *
 * @author murali
 */
public class SystemJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SystemJPanel
     */
    PatientDirectory pd;
    PersonDirectory p;
    public SystemJPanel(PatientDirectory pd, PersonDirectory p) {
        initComponents();
        
        this.pd = pd;
        this.p = p;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnPatients = new javax.swing.JButton();
        btnPersons = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setText("VIEW PATIENTS AND PERSONS");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 90, -1, -1));

        btnPatients.setText("PATIENTS");
        btnPatients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPatientsActionPerformed(evt);
            }
        });
        add(btnPatients, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 160, -1, -1));

        btnPersons.setText("PERSONS");
        btnPersons.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPersonsActionPerformed(evt);
            }
        });
        add(btnPersons, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 160, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "First Name", "Last Name", "Age", "Community"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, -1, 353));
    }// </editor-fold>//GEN-END:initComponents

    private void btnPatientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPatientsActionPerformed
        // TODO add your handling code here:
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        
        for( Patient obj : pd.getPatientDirectory()){
           
                
                Object[] row = new Object[4];
                row[0] = obj.getPatientFirstName();
                row[1] = obj.getPatientLastName();
                row[2] = obj.getPatientNumber();
                row[3] = obj.getPin();
                
                model.addRow(row);
              
        }
    }//GEN-LAST:event_btnPatientsActionPerformed

    private void btnPersonsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPersonsActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        
        for( Person obj : p.getPersonDirectory()){
           
                
                Object[] row = new Object[4];
                row[0] = obj.getFirstName();
                row[1] = obj.getLastName();
                row[2] = obj.getAge();
                row[3] = obj.getPin();
                
                model.addRow(row);
        }
    }//GEN-LAST:event_btnPersonsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPatients;
    private javax.swing.JButton btnPersons;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
