/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import model.Car;
import model.CarList;
//import java.lang.System.Linq; 


/**
 *
 * @author murali
 */
public class CreateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form addJPanel
     */
    
    CarList carList;
    public CreateJPanel(CarList carList) {
        initComponents();
        
        this.carList = carList;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        lblTitle = new javax.swing.JLabel();
        lblManufacturerYear = new javax.swing.JLabel();
        lblNumberOfSeats = new javax.swing.JLabel();
        lblManufacturerName = new javax.swing.JLabel();
        lblModelNumber = new javax.swing.JLabel();
        lblSerialNumber = new javax.swing.JLabel();
        lblCertificateExpiry = new javax.swing.JLabel();
        lblCity = new javax.swing.JLabel();
        lblAvailability = new javax.swing.JLabel();
        btnSubmit = new javax.swing.JButton();
        txtManufacturerName = new javax.swing.JTextField();
        txtSeats = new javax.swing.JTextField();
        txtSerialNumber = new javax.swing.JTextField();
        txtModelNumber = new javax.swing.JTextField();
        txtCity = new javax.swing.JTextField();
        txtExpiryCertificate = new javax.swing.JTextField();
        txtManufacturerYear = new javax.swing.JTextField();
        jRadioButtonYes = new javax.swing.JRadioButton();
        jRadioButtonNo = new javax.swing.JRadioButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblTitle.setText("ADD VEHICLE DETAILS");
        add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(267, 40, -1, -1));

        lblManufacturerYear.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        lblManufacturerYear.setText("VEHICLE MANUFACTURER YEAR:");
        add(lblManufacturerYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, -1, -1));

        lblNumberOfSeats.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        lblNumberOfSeats.setText("NUMBER OF SEATS:");
        add(lblNumberOfSeats, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, -1, -1));

        lblManufacturerName.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        lblManufacturerName.setText("VEHICLE MANUFACTURER NAME:");
        add(lblManufacturerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, -1, -1));

        lblModelNumber.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        lblModelNumber.setText("VEHICLE MODEL NUMBER:");
        add(lblModelNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 380, -1, -1));

        lblSerialNumber.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        lblSerialNumber.setText("VEHICLE SERIAL NUMBER:");
        add(lblSerialNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 320, -1, -1));

        lblCertificateExpiry.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        lblCertificateExpiry.setText("MAINTENANCE CERTIFICATE EXPIRY DATE:");
        add(lblCertificateExpiry, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 490, -1, -1));

        lblCity.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        lblCity.setText("CITY:");
        add(lblCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 430, -1, -1));

        lblAvailability.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        lblAvailability.setText("VEHICLE AVAILABILITY:");
        add(lblAvailability, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 540, -1, -1));

        btnSubmit.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        btnSubmit.setText("ADD VEHICLE");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        add(btnSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 630, -1, -1));

        txtManufacturerName.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        add(txtManufacturerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 150, 136, 30));

        txtSeats.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        add(txtSeats, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 260, 136, -1));

        txtSerialNumber.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        txtSerialNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSerialNumberActionPerformed(evt);
            }
        });
        add(txtSerialNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 320, 136, -1));

        txtModelNumber.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        add(txtModelNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 370, 136, -1));

        txtCity.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        add(txtCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 420, 136, -1));

        txtExpiryCertificate.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        add(txtExpiryCertificate, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 480, 136, -1));

        txtManufacturerYear.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        add(txtManufacturerYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 210, 136, -1));

        buttonGroup1.add(jRadioButtonYes);
        jRadioButtonYes.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        jRadioButtonYes.setText("Yes");
        jRadioButtonYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonYesActionPerformed(evt);
            }
        });
        add(jRadioButtonYes, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 540, -1, -1));

        buttonGroup1.add(jRadioButtonNo);
        jRadioButtonNo.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        jRadioButtonNo.setText("No");
        add(jRadioButtonNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 540, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void txtSerialNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSerialNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSerialNumberActionPerformed

    private void jRadioButtonYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonYesActionPerformed
       
    }//GEN-LAST:event_jRadioButtonYesActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        
        try{
        String manufacturerName = txtManufacturerName.getText();
        String manufacturerYear = txtManufacturerYear.getText();
        int seats = Integer.parseInt(txtSeats.getText());
        String serialNumber = txtSerialNumber.getText();
        String modelNumber = txtModelNumber.getText();
        String city = txtCity.getText();
        String expiryDate = txtExpiryCertificate.getText();
        
        if(manufacturerName.trim().isEmpty() || manufacturerYear.trim().isEmpty()||
           serialNumber.trim().isEmpty() || modelNumber.trim().isEmpty() || city.trim().isEmpty() || expiryDate.trim().isEmpty()){
            
            JOptionPane.showMessageDialog(null,"Please enter all fields! Some fields are required");
            return;
        }
        
        String avail="";
        
        if(jRadioButtonYes.isSelected()){
            avail="yes";
        }
        if(jRadioButtonNo.isSelected()){
            avail="no";
        }
        
        for( Car obj : carList.getCarList()){
            String serial = obj.getCarNumber();
            if(serial.equalsIgnoreCase(serialNumber)){
                JOptionPane.showMessageDialog(this, "Car serial number already exists");
                return;
            }
        }
        
        Car c = carList.addNewCars();
        
        
        c.setAvailability(avail);
        c.setCarNumber(serialNumber);
        c.setCity(city);
        c.setExpiryCertificate(expiryDate);
        c.setManufacturedYear(Integer.parseInt(manufacturerYear));
        c.setLastUpdate(expiryDate);
        c.setManufacturer(manufacturerName);
        c.setModelNumber(modelNumber);
        c.setSeats(seats);
        
        }catch(Exception e){
            JOptionPane.showMessageDialog(this,"Please check all inputs");
            return;
        }
        
        JOptionPane.showMessageDialog(this,"Vehicle added");
        
        txtManufacturerName.setText("");
        txtManufacturerYear.setText("");
        txtSeats.setText("");
        txtSerialNumber.setText("");
        txtModelNumber.setText("");
        txtCity.setText("");
        txtExpiryCertificate.setText("");
    }//GEN-LAST:event_btnSubmitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSubmit;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton jRadioButtonNo;
    private javax.swing.JRadioButton jRadioButtonYes;
    private javax.swing.JLabel lblAvailability;
    private javax.swing.JLabel lblCertificateExpiry;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblManufacturerName;
    private javax.swing.JLabel lblManufacturerYear;
    private javax.swing.JLabel lblModelNumber;
    private javax.swing.JLabel lblNumberOfSeats;
    private javax.swing.JLabel lblSerialNumber;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtExpiryCertificate;
    private javax.swing.JTextField txtManufacturerName;
    private javax.swing.JTextField txtManufacturerYear;
    private javax.swing.JTextField txtModelNumber;
    private javax.swing.JTextField txtSeats;
    private javax.swing.JTextField txtSerialNumber;
    // End of variables declaration//GEN-END:variables
}
