/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.util.ArrayList;
import java.util.stream.Collectors;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Car;
import model.CarList;

/**
 *
 * @author murali
 */
public class SearchJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SearchJPanel
     */
    
    CarList carList;
    public SearchJPanel(CarList carList) {
        initComponents();
        this.carList = carList;
        Availablity();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        btnCarAvailability = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnManufacturerName = new javax.swing.JButton();
        txtManuName = new javax.swing.JTextField();
        btnManufacturedYear = new javax.swing.JButton();
        txtManuYear = new javax.swing.JTextField();
        btnSeats = new javax.swing.JButton();
        txtMaxSeat = new javax.swing.JTextField();
        txtMinSeat = new javax.swing.JTextField();
        btnSerial = new javax.swing.JButton();
        txtSerial = new javax.swing.JTextField();
        btnModel = new javax.swing.JButton();
        txtModel = new javax.swing.JTextField();
        btnCity = new javax.swing.JButton();
        txtCity = new javax.swing.JTextField();
        btnExpiry = new javax.swing.JButton();
        txtExpiry = new javax.swing.JTextField();
        btnListAll = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox<>();
        btnFirstAvail = new javax.swing.JButton();
        txtFirstAvail = new javax.swing.JTextField();
        lblAvailCars = new javax.swing.JLabel();
        lblNotAvailCars = new javax.swing.JLabel();
        txtAvailYes = new javax.swing.JTextField();
        txtAvailNo = new javax.swing.JTextField();

        setBackground(new java.awt.Color(204, 204, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblTitle.setText("VEHICLE DETAILS");
        add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 70, -1, -1));

        btnCarAvailability.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        btnCarAvailability.setText("FIND ALL AVAILABLE CARS");
        btnCarAvailability.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarAvailabilityActionPerformed(evt);
            }
        });
        add(btnCarAvailability, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 320, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Manufacturer Name", "Manufacturer Year", "Number of Seats", "Serial Number", "Model Number", "City", "Certificate Expiry Date", "Availability"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 1010, 150));

        btnManufacturerName.setFont(new java.awt.Font("Lucida Grande", 1, 15)); // NOI18N
        btnManufacturerName.setText("CAR MANUFACTURED BY");
        btnManufacturerName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManufacturerNameActionPerformed(evt);
            }
        });
        add(btnManufacturerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 499, 240, 30));
        add(txtManuName, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 500, 110, -1));

        btnManufacturedYear.setFont(new java.awt.Font("Lucida Grande", 1, 15)); // NOI18N
        btnManufacturedYear.setText("CAR MANUFACTURED IN");
        btnManufacturedYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManufacturedYearActionPerformed(evt);
            }
        });
        add(btnManufacturedYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 539, 240, 30));
        add(txtManuYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 540, 110, -1));

        btnSeats.setFont(new java.awt.Font("Lucida Grande", 1, 15)); // NOI18N
        btnSeats.setText("NUMBER OF SEATS");
        btnSeats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeatsActionPerformed(evt);
            }
        });
        add(btnSeats, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 580, 240, -1));
        add(txtMaxSeat, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 580, 50, -1));
        add(txtMinSeat, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 580, 50, -1));

        btnSerial.setFont(new java.awt.Font("Lucida Grande", 1, 15)); // NOI18N
        btnSerial.setText("CAR SERIAL NUMBER ");
        btnSerial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSerialActionPerformed(evt);
            }
        });
        add(btnSerial, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 620, 240, -1));
        add(txtSerial, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 620, 110, -1));

        btnModel.setFont(new java.awt.Font("Lucida Grande", 1, 15)); // NOI18N
        btnModel.setText("CAR MODEL NUMBER ");
        btnModel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModelActionPerformed(evt);
            }
        });
        add(btnModel, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 660, 240, -1));
        add(txtModel, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 660, 110, -1));

        btnCity.setFont(new java.awt.Font("Lucida Grande", 1, 15)); // NOI18N
        btnCity.setText("CITY");
        btnCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCityActionPerformed(evt);
            }
        });
        add(btnCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 700, 240, -1));
        add(txtCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 700, 110, -1));

        btnExpiry.setFont(new java.awt.Font("Lucida Grande", 1, 15)); // NOI18N
        btnExpiry.setText("CERTIFICATE EXPIRY YEAR");
        btnExpiry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExpiryActionPerformed(evt);
            }
        });
        add(btnExpiry, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 740, 240, -1));
        add(txtExpiry, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 740, 110, -1));

        btnListAll.setFont(new java.awt.Font("Lucida Grande", 1, 15)); // NOI18N
        btnListAll.setText("LIST ALL MANUFACTURERS");
        btnListAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListAllActionPerformed(evt);
            }
        });
        add(btnListAll, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 780, 240, -1));

        add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 780, 130, -1));

        btnFirstAvail.setFont(new java.awt.Font("Lucida Grande", 1, 15)); // NOI18N
        btnFirstAvail.setText("FIRST AVAILABLE CAR IN");
        btnFirstAvail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFirstAvailActionPerformed(evt);
            }
        });
        add(btnFirstAvail, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 459, 240, 30));
        add(txtFirstAvail, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 460, 110, -1));

        lblAvailCars.setText("Available");
        add(lblAvailCars, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 310, 130, 30));

        lblNotAvailCars.setText("Not Available");
        add(lblNotAvailCars, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 340, 160, 30));

        txtAvailYes.setEditable(false);
        add(txtAvailYes, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 310, 190, -1));

        txtAvailNo.setEditable(false);
        add(txtAvailNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 340, 190, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnCarAvailabilityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarAvailabilityActionPerformed
        // TODO add your handling code here:
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        
        for( Car obj : carList.getCarList()){
            if( obj.getAvailability().equals("yes")){
                
                Object[] row = new Object[8];
                row[0] = obj;
                row[1] = obj.getManufacturedYear();
                row[2] = String.valueOf(obj.getSeats());
                row[3] = obj.getCarNumber();
                row[4] = obj.getModelNumber();
                row[5] = obj.getCity();
                row[6] = obj.getExpiryCertificate();
                row[7] = obj.getAvailability();
                
                model.addRow(row);
            }     
        }
    }//GEN-LAST:event_btnCarAvailabilityActionPerformed

    private void btnManufacturerNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManufacturerNameActionPerformed
        // TODO add your handling code here:
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        int count=0;
        String manuName = txtManuName.getText();
        for( Car obj : carList.getCarList()){
            if( obj.getManufacturer().equalsIgnoreCase(manuName)){
                Object[] row = new Object[8];
                row[0] = obj;
                row[1] = obj.getManufacturedYear();
                row[2] = String.valueOf(obj.getSeats());
                row[3] = obj.getCarNumber();
                row[4] = obj.getModelNumber();
                row[5] = obj.getCity();
                row[6] = obj.getExpiryCertificate();
                row[7] = obj.getAvailability();
                
                model.addRow(row);
                count++;
            }
        }
        
        if ( count == 0 )
            JOptionPane.showMessageDialog(null, " Sorry no cars available by "+manuName);
        
        txtManuName.setText("");
    }//GEN-LAST:event_btnManufacturerNameActionPerformed

    private void btnManufacturedYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManufacturedYearActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        
        int count=0;
        
        int manuYear = Integer.parseInt(txtManuYear.getText());
        for( Car obj : carList.getCarList()){
            if( obj.getManufacturedYear()==(manuYear)){
                Object[] row = new Object[8];
                row[0] = obj;
                row[1] = obj.getManufacturedYear();
                row[2] = String.valueOf(obj.getSeats());
                row[3] = obj.getCarNumber();
                row[4] = obj.getModelNumber();
                row[5] = obj.getCity();
                row[6] = obj.getExpiryCertificate();
                row[7] = obj.getAvailability();
                
                model.addRow(row);
                count++;
            }
        }
        
        if ( count == 0 )
            JOptionPane.showMessageDialog(null, " Sorry no cars available manufactured in "+manuYear);
        
        txtManuYear.setText("");
    }//GEN-LAST:event_btnManufacturedYearActionPerformed

    private void btnSeatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeatsActionPerformed
        // TODO add your handling code here:
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        
        int count=0;
        
        int min = Integer.parseInt(txtMinSeat.getText());
        int max = Integer.parseInt(txtMaxSeat.getText());
        
        for( Car obj : carList.getCarList()){
            if( obj.getSeats()>=min && obj.getSeats()<=max){
                Object[] row = new Object[8];
                row[0] = obj;
                row[1] = obj.getManufacturedYear();
                row[2] = String.valueOf(obj.getSeats());
                row[3] = obj.getCarNumber();
                row[4] = obj.getModelNumber();
                row[5] = obj.getCity();
                row[6] = obj.getExpiryCertificate();
                row[7] = obj.getAvailability();
                
                model.addRow(row);
                count++;
            }
        }
        
        if ( count == 0 )
            JOptionPane.showMessageDialog(null, "Sorry no cars with minimum seats "+min+" and maximum seats "+max);
        
        txtMinSeat.setText("");
        txtMaxSeat.setText("");
    }//GEN-LAST:event_btnSeatsActionPerformed

    private void btnSerialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSerialActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        
        int count=0;
        
        String serial = txtSerial.getText();
        
        for( Car obj : carList.getCarList()){
            if( obj.getCarNumber().equalsIgnoreCase(serial)){
                Object[] row = new Object[8];
                row[0] = obj;
                row[1] = obj.getManufacturedYear();
                row[2] = String.valueOf(obj.getSeats());
                row[3] = obj.getCarNumber();
                row[4] = obj.getModelNumber();
                row[5] = obj.getCity();
                row[6] = obj.getExpiryCertificate();
                row[7] = obj.getAvailability();
                
                model.addRow(row);
                count++;
            }
        }
        
        if ( count == 0 )
            JOptionPane.showMessageDialog(null, "Sorry no cars available with serial number "+serial);
        
        txtSerial.setText("");
        
    }//GEN-LAST:event_btnSerialActionPerformed

    private void btnModelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModelActionPerformed
        // TODO add your handling code here:
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        
        int count=0;
        
        String modelNumber = txtModel.getText();
        
        for( Car obj : carList.getCarList()){
            if( obj.getModelNumber().equalsIgnoreCase(modelNumber)){
                Object[] row = new Object[8];
                row[0] = obj;
                row[1] = obj.getManufacturedYear();
                row[2] = String.valueOf(obj.getSeats());
                row[3] = obj.getCarNumber();
                row[4] = obj.getModelNumber();
                row[5] = obj.getCity();
                row[6] = obj.getExpiryCertificate();
                row[7] = obj.getAvailability();
                
                model.addRow(row);
                count++;
            }
        }
        
        if ( count == 0 )
            JOptionPane.showMessageDialog(null, "Sorry no cars available with model number "+modelNumber);
        
        txtModel.setText("");
    }//GEN-LAST:event_btnModelActionPerformed

    private void btnCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCityActionPerformed
        // TODO add your handling code here:
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        
        int count=0;
        
        String city = txtCity.getText();
        
        for( Car obj : carList.getCarList()){
            if( obj.getCity().equalsIgnoreCase(city)){
                Object[] row = new Object[8];
                row[0] = obj;
                row[1] = obj.getManufacturedYear();
                row[2] = String.valueOf(obj.getSeats());
                row[3] = obj.getCarNumber();
                row[4] = obj.getModelNumber();
                row[5] = obj.getCity();
                row[6] = obj.getExpiryCertificate();
                row[7] = obj.getAvailability();
                
                model.addRow(row);
                count++;
            }
        }
        
        if ( count == 0 )
            JOptionPane.showMessageDialog(null, "Sorry no cars available in "+city);
        
        txtCity.setText("");
    }//GEN-LAST:event_btnCityActionPerformed

    private void btnExpiryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExpiryActionPerformed
        // TODO add your handling code here:
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        
        int count=0;
        
        int expiry = Integer.parseInt(txtExpiry.getText());
        
        for( Car obj : carList.getCarList()){
            if( Integer.parseInt(obj.getExpiryCertificate()) < expiry){
                Object[] row = new Object[8];
                row[0] = obj;
                row[1] = obj.getManufacturedYear();
                row[2] = String.valueOf(obj.getSeats());
                row[3] = obj.getCarNumber();
                row[4] = obj.getModelNumber();
                row[5] = obj.getCity();
                row[6] = obj.getExpiryCertificate();
                row[7] = obj.getAvailability();
                
                model.addRow(row);
                count++;
            }
        }
        
        if ( count == 0 )
            JOptionPane.showMessageDialog(null, "Sorry no cars with expiry certificate on "+expiry);
        
        txtExpiry.setText("");
    }//GEN-LAST:event_btnExpiryActionPerformed

    private void btnListAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListAllActionPerformed
        // TODO add your handling code here:

        ArrayList<String> list = new ArrayList<>();
        
        for( Car obj : carList.getCarList()){
            if(!(list.contains(obj.getManufacturer()))){
                    Object[] row = new Object[1];
                    row[0] = obj.getManufacturer();
                    list.add(obj.getManufacturer());
                    jComboBox2.addItem(obj.getManufacturer());
            }
        }
        
        
        
        
    }//GEN-LAST:event_btnListAllActionPerformed

    private void btnFirstAvailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirstAvailActionPerformed
        // TODO add your handling code here:
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        
        int count=0;
        
        String availCar = txtFirstAvail.getText();
        
        for( Car obj : carList.getCarList()){
            if( obj.getAvailability().equalsIgnoreCase("yes") && obj.getCity().equalsIgnoreCase(availCar)){
                Object[] row = new Object[8];
                row[0] = obj;
                row[1] = obj.getManufacturedYear();
                row[2] = String.valueOf(obj.getSeats());
                row[3] = obj.getCarNumber();
                row[4] = obj.getModelNumber();
                row[5] = obj.getCity();
                row[6] = obj.getExpiryCertificate();
                row[7] = obj.getAvailability();
                
                model.addRow(row);
                count++;
                return;
            }
        }
        
        if ( count == 0 )
            JOptionPane.showMessageDialog(null, "Sorry no cars available in  "+availCar);
        
        txtFirstAvail.setText("");
    }//GEN-LAST:event_btnFirstAvailActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCarAvailability;
    private javax.swing.JButton btnCity;
    private javax.swing.JButton btnExpiry;
    private javax.swing.JButton btnFirstAvail;
    private javax.swing.JButton btnListAll;
    private javax.swing.JButton btnManufacturedYear;
    private javax.swing.JButton btnManufacturerName;
    private javax.swing.JButton btnModel;
    private javax.swing.JButton btnSeats;
    private javax.swing.JButton btnSerial;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblAvailCars;
    private javax.swing.JLabel lblNotAvailCars;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtAvailNo;
    private javax.swing.JTextField txtAvailYes;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtExpiry;
    private javax.swing.JTextField txtFirstAvail;
    private javax.swing.JTextField txtManuName;
    private javax.swing.JTextField txtManuYear;
    private javax.swing.JTextField txtMaxSeat;
    private javax.swing.JTextField txtMinSeat;
    private javax.swing.JTextField txtModel;
    private javax.swing.JTextField txtSerial;
    // End of variables declaration//GEN-END:variables

    private void Availablity() {
        
        
        int countYes=0;
        int countNo=0;
        
        
        for( Car obj : carList.getCarList()){
            if( obj.getAvailability().equals("yes")){
                countYes++;
            }
            else if(obj.getAvailability().equals("no")){
                countNo++;
            }
        }
        txtAvailYes.setText(countYes+" cars available");
        txtAvailNo.setText(countNo+" cars unavailable");
    }
    
}
