/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Car;
import model.CarList;

/**
 *
 * @author murali
 */
public class ViewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewJPanel
     */
    
    CarList carList;
    public ViewJPanel(CarList carList) {
        initComponents();
        
        this.carList= carList;
        
//        prePopulate();
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblView = new javax.swing.JTable();
        btnView = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        txtManufacturerName = new javax.swing.JTextField();
        txtSeats = new javax.swing.JTextField();
        lblManufacturerYear = new javax.swing.JLabel();
        txtSerialNumber = new javax.swing.JTextField();
        lblNumberOfSeats = new javax.swing.JLabel();
        txtModelNumber = new javax.swing.JTextField();
        lblManufacturerName = new javax.swing.JLabel();
        txtCity = new javax.swing.JTextField();
        lblModelNumber = new javax.swing.JLabel();
        txtExpiryCertificate = new javax.swing.JTextField();
        lblSerialNumber = new javax.swing.JLabel();
        txtManufacturerYear = new javax.swing.JTextField();
        lblCertificateExpiry = new javax.swing.JLabel();
        lblCity = new javax.swing.JLabel();
        btnupdate = new javax.swing.JButton();
        jRadioButtonYes = new javax.swing.JRadioButton();
        jRadioButtonNo = new javax.swing.JRadioButton();
        lblAvailability1 = new javax.swing.JLabel();

        lblTitle.setText("VIEW VEHICLE INFORMATION");

        tblView.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Manufacturer Name", "Serial Number", "ModelNumber", "City", "Availability"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblView);

        btnView.setText("VIEW");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        btnDelete.setText("DELETE");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        lblManufacturerYear.setText("VEHICLE MANUFACTURER YEAR:");

        txtSerialNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSerialNumberActionPerformed(evt);
            }
        });

        lblNumberOfSeats.setText("NUMBER OF SEATS:");

        lblManufacturerName.setText("VEHICLE MANUFACTURER NAME:");

        lblModelNumber.setText("VEHICLE MODEL NUMBER:");

        lblSerialNumber.setText("VEHICLE SERIAL NUMBER:");

        lblCertificateExpiry.setText("MAINTENANCE CERTIFICATE EXPIRY DATE:");

        lblCity.setText("CITY:");

        btnupdate.setText("UPDATE");
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });

        jRadioButtonYes.setText("Yes");
        jRadioButtonYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonYesActionPerformed(evt);
            }
        });

        jRadioButtonNo.setText("No");

        lblAvailability1.setText("VEHICLE AVAILABILITY:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(267, 267, 267)
                        .addComponent(lblTitle))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(299, 299, 299)
                        .addComponent(btnView)
                        .addGap(15, 15, 15)
                        .addComponent(btnDelete)
                        .addGap(11, 11, 11)
                        .addComponent(btnupdate))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(lblCertificateExpiry)
                        .addGap(12, 12, 12)
                        .addComponent(txtExpiryCertificate, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(82, 82, 82)
                        .addComponent(lblNumberOfSeats)
                        .addGap(18, 18, 18)
                        .addComponent(txtSeats, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblAvailability1)
                            .addGap(6, 6, 6)
                            .addComponent(jRadioButtonYes)
                            .addGap(16, 16, 16)
                            .addComponent(jRadioButtonNo))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(76, 76, 76)
                                    .addComponent(lblManufacturerYear)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtManufacturerYear, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(42, 42, 42)
                                    .addComponent(lblSerialNumber))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(115, 115, 115)
                                    .addComponent(lblModelNumber)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtModelNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(162, 162, 162)
                                    .addComponent(lblCity))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(76, 76, 76)
                                    .addComponent(lblManufacturerName)
                                    .addGap(12, 12, 12)
                                    .addComponent(txtManufacturerName, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtSerialNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblTitle)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnupdate)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnView)
                                    .addComponent(btnDelete))))
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtManufacturerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(lblManufacturerName))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(lblAvailability1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jRadioButtonYes, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jRadioButtonNo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(lblModelNumber))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(txtModelNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblCity, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(lblManufacturerYear))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(txtManufacturerYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblSerialNumber)
                        .addComponent(txtSerialNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(lblCertificateExpiry))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(txtExpiryCertificate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNumberOfSeats)
                            .addComponent(txtSeats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(74, 74, 74))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtSerialNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSerialNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSerialNumberActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:
        
        int selectedRowIndex = tblView.getSelectedRow();
        
        if ( selectedRowIndex < 0 ){
            JOptionPane.showMessageDialog(this,"Please select a row to view");
            return;
        }
        
        DefaultTableModel model = (DefaultTableModel) tblView.getModel();
        Car selectedCar = (Car) model.getValueAt(selectedRowIndex , 0);
        
        
        txtCity.setText(selectedCar.getCity());
        txtExpiryCertificate.setText(selectedCar.getExpiryCertificate());
        txtManufacturerName.setText(selectedCar.getManufacturer());
        txtManufacturerYear.setText(String.valueOf(selectedCar.getManufacturedYear()));
        txtModelNumber.setText(selectedCar.getModelNumber());
        txtSeats.setText(String.valueOf(selectedCar.getSeats()));
        txtSerialNumber.setText(selectedCar.getCarNumber());
      
        
    }//GEN-LAST:event_btnViewActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        
        int selectedRowIndex = tblView.getSelectedRow();
        
        if ( selectedRowIndex < 0 ){
            JOptionPane.showMessageDialog(this,"Please select a row to delete");
            return;
        }
        
        DefaultTableModel model = (DefaultTableModel) tblView.getModel();
        Car selectedCar = (Car) model.getValueAt(selectedRowIndex , 0);
        
        carList.deleteCar(selectedCar);

        JOptionPane.showMessageDialog(this,"Vehicle deleted");
        
        populateTable();
        
        ButtonGroup bg = new ButtonGroup();
        bg.add(jRadioButtonNo);
        bg.add(jRadioButtonYes);
        bg.clearSelection();
        txtManufacturerName.setText("");
        txtManufacturerYear.setText("");
        txtSeats.setText("");
        txtSerialNumber.setText("");
        txtModelNumber.setText("");
        txtCity.setText("");
        txtExpiryCertificate.setText("");
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void jRadioButtonYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonYesActionPerformed

    }//GEN-LAST:event_jRadioButtonYesActionPerformed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        // TODO add your handling code here:
        
        int selectedRowIndex = tblView.getSelectedRow();
        
        if ( selectedRowIndex < 0 ){
            JOptionPane.showMessageDialog(this,"Please select a row to update");
            return;
        }
        
        DefaultTableModel model = (DefaultTableModel) tblView.getModel();
        Car selectedCar = (Car) model.getValueAt(selectedRowIndex , 0);
        
        selectedCar.setCity(txtCity.getText());
        selectedCar.setExpiryCertificate(txtExpiryCertificate.getText());
        selectedCar.setManufacturer(txtManufacturerName.getText());
        selectedCar.setManufacturedYear(Integer.parseInt(txtManufacturerYear.getText()));
        selectedCar.setModelNumber(txtModelNumber.getText());
        selectedCar.setSeats(Integer.parseInt(txtSeats.getText()));
        selectedCar.setCarNumber(txtSerialNumber.getText());    
        
        String avail="";
        int availCheck = 0;
        
        ButtonGroup bg = new ButtonGroup();
        bg.add(jRadioButtonNo);
        bg.add(jRadioButtonYes);
        
        if(jRadioButtonYes.isSelected()){
            avail="yes";
        }
        else if(jRadioButtonNo.isSelected()){
            avail="no";
        }
        else{
            availCheck = 1;
        }
        
        if (availCheck == 0){
            selectedCar.setAvailability(avail);
            
        }
        
        
        populateTable();
        
        bg.clearSelection();
        txtManufacturerName.setText("");
        txtManufacturerYear.setText("");
        txtSeats.setText("");
        txtSerialNumber.setText("");
        txtModelNumber.setText("");
        txtCity.setText("");
        txtExpiryCertificate.setText("");
        
        Car obj = new Car();
        
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd HH:mm:ss");  
        LocalDateTime now = LocalDateTime.now();  
        System.out.println(dtf.format(now)); 
        String date = dtf.format(now);
        obj.setDate(date);
        
        
        
    }//GEN-LAST:event_btnupdateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnView;
    private javax.swing.JButton btnupdate;
    private javax.swing.JRadioButton jRadioButtonNo;
    private javax.swing.JRadioButton jRadioButtonYes;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAvailability1;
    private javax.swing.JLabel lblCertificateExpiry;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblManufacturerName;
    private javax.swing.JLabel lblManufacturerYear;
    private javax.swing.JLabel lblModelNumber;
    private javax.swing.JLabel lblNumberOfSeats;
    private javax.swing.JLabel lblSerialNumber;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblView;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtExpiryCertificate;
    private javax.swing.JTextField txtManufacturerName;
    private javax.swing.JTextField txtManufacturerYear;
    private javax.swing.JTextField txtModelNumber;
    private javax.swing.JTextField txtSeats;
    private javax.swing.JTextField txtSerialNumber;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {
        
        DefaultTableModel model = (DefaultTableModel) tblView.getModel();
        model.setRowCount(0);
        
        for ( Car c : carList.getCarList()){
            
            Object[] row = new Object[5];
            row[0] = c;
            row[1] = c.getCarNumber();
            row[2] = c.getModelNumber();
            row[3] = c.getCity();
            row[4] = c.getAvailability();
            
            model.addRow(row);
        }
    }
}
